title: Garrick Wong
description: DevOps | Cloud | QA | IT
baseurl: ""
url: https://garrickw.com

theme: cvless

# site settings
taglong: DevOps | Cloud | QA | IT
tagshort: DevOps | Cloud | QA | IT

# author settings
author:
  name: Garrick Wong
  email: me@garrickw.com
photo: assets/files/photo.jpg
address: Toronto, Canada
phone: +1 647 230 2926

# social media links
social:
  github: w1rule
  linkedin: garrick-w
  projects: projects

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
